# .github/workflows/deploy.yml
name: Deploy to DigitalOcean Kubernetes

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Set up DigitalOcean CLI and kubectl
      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Step 2: Install kubectl and configure it for DigitalOcean Kubernetes
      - name: Install kubectl and configure kubeconfig
        run: doctl kubernetes cluster kubeconfig save k8s-tumble

      # Step 3: Deploy to Kubernetes using kubectl
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart deployment -n production tumble-backend
