# .github/workflows/deploy.yml
name: Deploy to DigitalOcean Kubernetes

on:
  workflow_call:

env:
  KUBECONF: ${{ secrets.KUBECONF }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code (to access Kubernetes manifests)
      - name: Check out code
        uses: actions/checkout@v2

      - name: Pull kubeconfig
        run: |
          echo "$KUBECONF" > kubeconfig

      # Step 2: Set up DigitalOcean CLI and kubectl
      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Step 3: Install kubectl and configure it for DigitalOcean Kubernetes
      - name: Install kubectl and configure kubeconfig
        run: doctl kubernetes cluster kubeconfig save do-ams3-k8s-tumble

      # Step 4: Deploy to Kubernetes using kubectl
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f tumble-cluster/kubernetes/backend/deployment.yml
          kubectl apply -f tumble-cluster/kubernetes/backend/service.yml
