# .github/workflows/deploy.yml
name: Deploy to DigitalOcean Kubernetes

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code (to access Kubernetes manifests)
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBECONF }}" > $HOME/.kube/config

      # Step 2: Set up DigitalOcean CLI and kubectl
      - name: Set up DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # Step 3: Install kubectl and configure it for DigitalOcean Kubernetes
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"

      # Step 4: Deploy to Kubernetes using kubectl
      - name: Deploy to Kubernetes
        run: |
          kubectl rollout restart
