# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  pull_request:
    branches: 
      - main
    types: [closed]

jobs:
  publish-docker:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write

  deploy:
    if: ${{ github.event.pull_request.merged }}
    needs: publish-docker
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
