# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main  # Adjust based on your branch

jobs:
  publish-docker:
    uses: ./.github/workflows/docker-image.yml

  deploy:
    needs: publish-docker
    uses: ./.github/workflows/deploy.yml
