# .github/workflows/main.yml
name: CI/CD Pipeline

on:
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - 'main'

jobs:
  publish-docker:
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
      id-token: write

  deploy:
    needs: publish-docker
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
